//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class air_conditioner
    {
        public int Air_Conditioner_Id { get; set; }
        public string ApplStandard { get; set; }
        public string MEPSComp { get; set; }
        public string N_Standard { get; set; }
        public string Model_No { get; set; }
        public string Family_Name { get; set; }
        public Nullable<int> avg_pwr_standby_mode { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> C_Dehumid_Rated { get; set; }
        public string Configuration1 { get; set; }
        public string Configuration2 { get; set; }
        public string Configuration2_unitmount { get; set; }
        public string Configuration3_Sink { get; set; }
        public string Configuration3_Source { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> C_Power_Inp_Rated { get; set; }
        public Nullable<decimal> C_Sens_Cool_Rated { get; set; }
        public Nullable<decimal> C_Total_Cool_Rated { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<decimal> H2_COP { get; set; }
        public Nullable<decimal> H2_HeatPwrCapacity { get; set; }
        public Nullable<decimal> H2_HeatPwrInput { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> H_Power_Inp_Rated { get; set; }
        public Nullable<decimal> H_Total_Heat_Rated { get; set; }
        public string indoorType { get; set; }
        public Nullable<decimal> EERtestAvg { get; set; }
        public Nullable<decimal> COPtestAvg { get; set; }
        public string Invert { get; set; }
        public Nullable<decimal> Setting_cool { get; set; }
        public Nullable<int> Setting_heat { get; set; }
        public Nullable<decimal> Pnoc { get; set; }
        public Nullable<decimal> Pnoh { get; set; }
        public Nullable<decimal> VSCP_EER50 { get; set; }
        public Nullable<decimal> VSCP_COP50 { get; set; }
        public Nullable<decimal> AnnualOutputEER { get; set; }
        public Nullable<decimal> AnnualOutputCOP { get; set; }
        public Nullable<decimal> sri2010_cool { get; set; }
        public Nullable<decimal> sri2010_heat { get; set; }
        public Nullable<decimal> Star2010_Cool { get; set; }
        public Nullable<decimal> Star2010_Heat { get; set; }
        public string outdoortype { get; set; }
        public string Phase { get; set; }
        public string Refrigerant { get; set; }
        public string Sold_in { get; set; }
        public Nullable<int> Submit_ID { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> GrandDate { get; set; }
        public string SubmitStatus { get; set; }
        public string Type { get; set; }
        public Nullable<int> Width { get; set; }
        public string Product_Class { get; set; }
        public string Demand_Response_1 { get; set; }
        public string Demand_Response_2 { get; set; }
        public string Demand_Response_4 { get; set; }
        public string Demand_Response_5 { get; set; }
        public string Demand_Response_6 { get; set; }
        public string Demand_Response_7 { get; set; }
        public string PartNumber { get; set; }
        public Nullable<decimal> EER { get; set; }
        public string Availability_Status { get; set; }
        public Nullable<int> star2000_cool { get; set; }
        public Nullable<int> star2000_heat { get; set; }
        public string Product_Website { get; set; }
        public string Representative_Brand_URL { get; set; }
        public string Variable_Output_Compressor { get; set; }
        public string Star_Image_Large { get; set; }
        public string Star_Image_Small { get; set; }
        public string Registration_Number { get; set; }
        public string Is_variable_speed { get; set; }
        public string Type_variable_output { get; set; }
        public string Var_output_compressor { get; set; }
        public Nullable<decimal> Rated_cooling_power_input_kW { get; set; }
        public Nullable<decimal> Rated_heating_power_input_kW { get; set; }
        public Nullable<decimal> Rated_AEER { get; set; }
        public Nullable<decimal> Rated_ACOP { get; set; }
        public Nullable<int> Type_Id { get; set; }
    
        public virtual appliance_types appliance_types { get; set; }
    }
}
