//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dishwasher
    {
        public int Dishwasher_Id { get; set; }
        public string ApplStandard { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<int> CEC { get; set; }
        public string Conn_Type { get; set; }
        public string Country { get; set; }
        public string delayStartMode { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Load_Type { get; set; }
        public string Model_No { get; set; }
        public string Family_Name { get; set; }
        public string N_Standard { get; set; }
        public Nullable<decimal> New_SRI { get; set; }
        public Nullable<decimal> New_Star { get; set; }
        public Nullable<decimal> postProgenergy { get; set; }
        public Nullable<decimal> powerConsMode { get; set; }
        public string Prog_Name { get; set; }
        public Nullable<decimal> Prog_Time { get; set; }
        public string Sold_in { get; set; }
        public Nullable<decimal> standbyPowerUsage { get; set; }
        public Nullable<int> Submit_ID { get; set; }
        public string SubmitStatus { get; set; }
        public Nullable<decimal> Tot_Wat_Cons { get; set; }
        public string Type { get; set; }
        public string Water_Softener { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> GrandDate { get; set; }
        public string Product_Class { get; set; }
        public string Availability_Status { get; set; }
        public string Product_Website { get; set; }
        public string Representative_Brand_URL { get; set; }
        public Nullable<decimal> Water_Consumption_litres { get; set; }
        public Nullable<int> Star_Rating_old { get; set; }
        public string Star_Image_Large { get; set; }
        public string Star_Image_Small { get; set; }
        public Nullable<int> Type_Id { get; set; }
    
        public virtual appliance_types appliance_types { get; set; }
    }
}
