//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_recipes
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> preparation_time { get; set; }
        public string instructions { get; set; }
        public string ingredients { get; set; }
        public string difficulty_level { get; set; }
        public Nullable<bool> category_breakfast { get; set; }
        public Nullable<bool> category_lunch { get; set; }
        public Nullable<bool> category_dinner { get; set; }
        public Nullable<bool> category_dessert { get; set; }
    }
}
