//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herb
    {
        public int Herb_Id { get; set; }
        public string Herb_Categories { get; set; }
        public string Difficulty { get; set; }
        public string Soil_Environment { get; set; }
        public string Steps { get; set; }
        public string Growing_Time { get; set; }
        public string Where_to_buy { get; set; }
    }
}
