//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeftoverRecipesEntities : DbContext
    {
        public LeftoverRecipesEntities()
            : base("name=LeftoverRecipesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Food_recipes> Food_recipes { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<recipe_type> recipe_type { get; set; }
        public virtual DbSet<Herb> Herbs { get; set; }
    }
}
