//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        public int recipe_id { get; set; }
        public string name { get; set; }
        public string minutes { get; set; }
        public string steps { get; set; }
        public string ingredients { get; set; }
        public string difficulty_assignment { get; set; }
        public Nullable<int> recipe_type_id { get; set; }
    
        public virtual recipe_type recipe_type { get; set; }
    }
}
