//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class recycling_centres
    {
        public int centre_id { get; set; }
        public string Address { get; set; }

        [DisplayFormat(DataFormatString = "{0:###.########}")]
        public Nullable<decimal> Lattitude { get; set; }
        [DisplayFormat(DataFormatString = "{0:###.########}")]
        public Nullable<decimal> Longitude { get; set; }
    }
}
