//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvisionAGreenLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refrigerator
    {
        public int Refrigerator_Id { get; set; }
        public string Adaptive_Defrost { get; set; }
        public string ApplStandard { get; set; }
        public string Brand { get; set; }
        public Nullable<int> CEC { get; set; }
        public string CompartGrVol { get; set; }
        public string CompartNetVol { get; set; }
        public string CompartType { get; set; }
        public string Configuration { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> FF_Vol { get; set; }
        public Nullable<decimal> FZ_Vol { get; set; }
        public string Group { get; set; }
        public Nullable<int> Height { get; set; }
        public string Icemaker { get; set; }
        public string MEPSApproval { get; set; }
        public string Model_No { get; set; }
        public string Family_Name { get; set; }
        public string N_Standard { get; set; }
        public Nullable<decimal> Star2009 { get; set; }
        public Nullable<decimal> SRI2009 { get; set; }
        public Nullable<int> No_Doors { get; set; }
        public Nullable<decimal> S_MEPS_Ad { get; set; }
        public Nullable<decimal> S_MEPScutoff { get; set; }
        public string Sold_in { get; set; }
        public Nullable<int> Submit_ID { get; set; }
        public string SubmitStatus { get; set; }
        public Nullable<decimal> Tot_Vol { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> GrandDate { get; set; }
        public string Product_Class { get; set; }
        public string Availability_Status { get; set; }
        public string Product_Website { get; set; }
        public string Representative_Brand_URL { get; set; }
        public Nullable<decimal> Fixed_MEPS_allowance_factor { get; set; }
        public Nullable<decimal> Variable_MEPS_allowance_factor { get; set; }
        public Nullable<decimal> Adjusted_volume { get; set; }
        public string Type { get; set; }
        public Nullable<int> Star_Rating_old { get; set; }
        public string Star_Image_Large { get; set; }
        public string Star_Image_Small { get; set; }
        public string Registration_Number { get; set; }
        public Nullable<int> Type_Id { get; set; }
    
        public virtual appliance_types appliance_types { get; set; }
    }
}
